# Generated by Django 5.1.15 on 2026-02-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('users', '0003_remove_profile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User',
        ),
    ]
