# Generated by Django 5.1.15 on 2026-02-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('level_mood', models.FloatField()),
                ('level_anxiety', models.FloatField()),
                ('level_nervousness', models.FloatField()),
                ('level_stimulation', models.FloatField()),
                ('epizodes_psychotik', models.SmallIntegerField()),
                ('what_work', models.TextField()),
                ('type', models.CharField(choices=[('moods', 'Moods'), ('sleep', 'Sleep')], default='moods', max_length=6)),
            ],
        ),
    ]
