# Generated by Django 5.1.15 on 2026-02-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moods',
            name='epizodes_psychotik',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
