# Generated by Django 5.2.11 on 2026-02-27 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moods',
            name='epizodes_psychotik',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_pleasure', models.FloatField()),
                ('name', models.TextField()),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actions_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('id_actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actions')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Actions_plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('long', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('what_work', models.TextField(blank=True)),
                ('id_actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actions')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainGroups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moods_actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_executing', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minute_exe', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_actions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actions')),
                ('id_moods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moods')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('how_percent', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('how_much', models.PositiveIntegerField(blank=True, null=True)),
                ('type_of_portion', models.PositiveSmallIntegerField()),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Planned_drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portion', models.FloatField()),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_drugs', to=settings.AUTH_USER_MODEL)),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
            ],
        ),
        migrations.CreateModel(
            name='Sleep_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_flat', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('sleep_deep', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('sleep_rem', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('sleep_working', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('id_moods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moods')),
            ],
        ),
        migrations.CreateModel(
            name='Substances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equivalent', models.FloatField(blank=True, null=True)),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Substances_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
                ('id_substances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.substances')),
            ],
        ),
        migrations.CreateModel(
            name='Substances_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doseproduct', models.FloatField(blank=True, null=True)),
                ('mg_ug', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
                ('id_substances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.substances')),
            ],
        ),
        migrations.CreateModel(
            name='Usees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users_descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_descriptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.descriptions')),
                ('id_usees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usees')),
            ],
        ),
    ]
